### ISSUE TITLE
[FEATURE] Supporting rational numbers

### ISSUE THREAD

**Issue by Nephty** [Nephty/calculator-cucumber-2024#10]
**Describe the new functionality you would like to see**
It would be useful to have primitive built-in support for rational numbers in the calculator (e.g. 3/4, 12/7, ...). A rational number can be seen as a fraction of two integer numbers.
https://en.wikipedia.org/wiki/Rational_number

**Is your feature request related to a specific need or problem?**
The idea of this extension is NOT to consider such fractions as decimal floating point numbers (e.g. 0.75 instead of 3/4) as this will lead to a loss of precision (e.g. 1/3 = 0.333333... but it is not possible to represent an infinite sequence of numbers in the decimal notation).
So we need arithmetic operations that work directly over rational numbers to avoid such loss of precision.

**Additional context**
(Some languages, such as Scheme provide built-in support for rational numbers.)

**Comment by VionFrancois** [comment]
The feature was successfully added to the calculator

## Support for rational number

A division between two integers (or rational number) creates a rational number. A rational number is represented with 2 integers, which does not lead to a loss of precision as long as we work with integers and rational numbers

## Operations on the rationals number

Addition, subtraction, multiplication and division are supported between a rational number and other type of values

## Supporting the real numbers

As this feature could interact with the real number feature #7 , the operations need to support real numbers. If we make an operation between a rational number and a real number, the rational number is converted to a real number (with a possible loss of precision) and the result is computed between 2 real numbers.
It is equivalent to quitting the "rational mode" and entering the "real mode"

## Supporting real operations

Operations like sqrt, cos, sin, ... were included with the same approach as explained before. We convert the rational number to a real number and we make the operation on the real number. By doing this type of operation, we leave the "rational mode" and give the result in "real mode"

## Convert to real button

In addition to supporting the real numbers, a button was added to the GUI to convert a rational number to a real number.
