### ISSUE TITLE
Printer visitor has too high cyclomatic complexity

### ISSUE THREAD

**Issue by tommens** [Nephty/calculator-cucumber-2024#11]
** Issue **
The visit method in the Printer visitor has a high cyclomatic complexity. It contains a switch that contains a for loop that contains a conditional statement. This complexity can be reduced significantly. To start with, one solution would be to use Java Streams to iterate over the arguments of an expression. This will make the code look more readable, more elegant, and no longer requires the use of a loop.

** Classification **
quality improvement

**Comment by ThomasBernard28** [comment]
The issue is normally fixed, methods were extracted from visit() method in Printer class and Java streams used instead of loops.
