### ISSUE TITLE
[FEATURE] Add parser to the GUI

### ISSUE THREAD

**Issue by MrRose765** [Nephty/calculator-cucumber-2024#18]
**Describe the new functionality you would like to see**
We have to call the calculator when the user press "equals" and show it to the screen.

**Is your feature request related to a specific need or problem?**
The calculator is not function at the moment, we can't get the results of our expressions since the GUI is not yet linked with the parser

see #17 to know how to use the parser

**Comment by Nephty** [comment]
To do so : 

- Add read method in App class that gives the input string to the read method of its calculator attribute
- Call this new method in the controller
- Display the result accordingly
