### ISSUE TITLE
[FEATURE] Suporting real numbers

### ISSUE THREAD

**Issue by Nephty** [Nephty/calculator-cucumber-2024#7]
**Describe the new functionality you would like to see**
The current version of this code only provides support for integer arithmetic. We also would like to also have support for arithmetics on decimal/real numbers. One possibility would be to use float or double as internal type for such numbers, but I strongly suggest to use something like java.math.BigDecimal, which allows for artibrary-precision decimal numbers and also provides operations for arithmetic, scale manipulation, rounding, comparison, hashing, and format conversion.
Implementing this functionality should also include the following ones:

Very large or very small decimal numbers should be expressible more compactly using the scientific notation or E-notation. for example, 6.022E23 would be considered as is equivalent to 6.022×10^23, which would be written as 6022 followed by 20 zeroes in "traditional" notation of natural numbers. Similarly, 1.6E-35 would be considered equivalent to 1.6×10^(−35) which would be written as 0.00...00016 (with lots of zeroes after the floating point of the decimal number).
It should be possible to specify the precision of these decimal numbers (i.e., how many significant digits of a real number will be encoded). This precision can be fixed when constructing a calculator, but the application should be able to be configured with a given precision for decimal numbers. (It is left open for discussion whether it should be possible from within a running calculator itself to change the precision.)
When supporting arithmetics on real numbers, care should be taken when carrying out operations that may result in an error. E.g. 0.0 / 0.0 is a NaN, i.e. an undefined number; 1.0/0.0 is either +infinity or a division by zero error, depending on whether infinity is allowed/supported by the calculator; -1.0/0.0 would be -infinity or a division by zero error; taking the square root of a negative number is not allowed (NaN); taking the logarithm of a negative value is not allowed (NaN) and so on. A clean, generic and reusable solution needs to be found for all such cases; knowing that the same types of problems may also occur for other number domains (integer values; fractions; complex number; ...)
As supported on most scientific calculators, it should be possible to use and convert numbers from degrees or radians (the use of radians if often more intuitive and useful when working frequently with trigonometric functions like sin, cos, and so on).

**Comment by ThomasBernard28** [comment]
The feature was successfully added to the calculator

# Represent a number
A real number is represented by a `My Number` class. This class has 2 parameters `real` and `imaginary`. These two parameters are `AbstractValues`. In this case, the `imaginary` part is set to be 0.

# Precision
It has been decided to make the precision global for the whole calculator. To do so, it is instantiated in `App.java`. The default is set to 5 which means that the numbers are represented with at most five decimals.
![image](https://github.com/Nephty/calculator-cucumber-2024/assets/79205296/8bf01095-8f5e-4c99-856e-1b58c9971a24)

# Scientific notation
The scientific notation has been implemented such that the calculator returns it when the number is too big or too small, using the precision previously introduced. Furthermore, it is possible for the user to perform operations using it has its parsing has also been implemented.
![image](https://github.com/Nephty/calculator-cucumber-2024/assets/79205296/62bf5ad8-6703-4283-9e31-7f11facee038)

![image](https://github.com/Nephty/calculator-cucumber-2024/assets/79205296/f5015509-7e00-4ae6-b8a2-88b1590d4096)

# Supporting other operators

## Square root
The square root was implemented for real numbers, as complex numbers have also been implemented it doesn't return NaN when performed on a negative number.

## Natural logarithm (Ln)
Implemented to take as parameter and return real numbers. Returns Nan when the number is <= 0.#9 

# Conversion from Radian to Degree and vice-versa.
As a converter has been implemented for issue #10 a new type of conversion for Angles has been added which allows the user to compute conversion from Radian to Degree and vice versa.
